---
version: "3.7"

services:
  squid:
    build:
      dockerfile: $PWD/Dockerfile.squid
    restart: unless-stopped
    ports:
      - "3128:3128"
  tinyproxy:
    build:
      dockerfile: $PWD/Dockerfile.tiny
    restart: unless-stopped
    ports:
      - "8081:8081"
  caddy:
    build:
      dockerfile: $PWD/Dockerfile.caddy
    restart: unless-stopped
    ports:
      - "8080:8080"
